name: minecraft

services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-bedrock-server:latest
    stdin_open: true
    tty: true
    environment:
      EULA: "TRUE"
      LEVEL_NAME: "BEST ASS WORLD SEASON2"
      SERVER_NAME: "BEST ASS SERVER"
      LEVEL_SEED: "835314931"
      CORRECT_PLAYER_MOVEMENT: "true"
      SERVER_AUTHORITATIVE_BLOCK_BREAKING: "true"
      DIFFICULTY: "hard"
    volumes:
      - ./mcdata:/data
    expose:
      - 19132/udp
    networks:
      - fox_net
    restart: unless-stopped
