name: minecraft

services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-bedrock-server:latest
    stdin_open: true
    tty: true
    environment:
      EULA: "TRUE"
      LEVEL_NAME: "BEST ASS WORLD"
      CORRECT_PLAYER_MOVEMENT: "true"
      SERVER_AUTHORITATIVE_BLOCK_BREAKING: "true"
    volumes:
      - ./mcdata:/data
    expose:
      - 19132/udp
    networks:
      - minecraft_network
    restart: unless-stopped

networks:
  minecraft_network:
