name: portainer

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    expose:
      - 9000
    networks:
      - fox_net

volumes:
  portainer_data:
