name: ssh

services:
  ssh-server:
    image: linuxserver/openssh-server:latest
    container_name: ssh-server
    hostname: ssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD_ACCESS=true
      - USER_NAME=Dfox
      - SUDO_ACCESS=false
      - USER_PASSWORD=password
    networks:
      - fox_net
    expose:
      - 2222
    restart: unless-stopped

  wetty:
    image: wettyoss/wetty
    container_name: wetty
    environment:
      - SSHHOST=ssh-server
      - SSHPORT=2222
      - SSHUSER=Dfox
      - BASE=/ssh
    networks:
      - fox_net
    expose:
      - 3000
    restart: unless-stopped
