name: xmpp-web

services:
  xmpp-web:
    container_name: xmpp-web
    image: nioc/xmpp-web:latest
    expose:
      - 80
    environment:
      - APP_IS_TRANSPORTS_USER_ALLOWED=true
    networks:
      - fox_net
    restart: unless-stopped
